version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_SERVER
      - DB_USER
      - DB_PASS
      - DB_NAME
    ports:
      - ${MAIN_PORT}:80
    volumes:
      - .:/var/www/html/
      - ./uploads:/var/www/html/uploads

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: msl_db
    # ports:
    # - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./database/msl_db.sql:/docker-entrypoint-initdb.d/start.sql

  # adminer:
  # image: adminer
  # restart: always
  # ports:
  # - 8080:8080

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql-data:
  uploads:
